export const data = {
  type: "FeatureCollection",
  metadata: {
    generated: 1703955562000,
    url: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson",
    title: "USGS Magnitude 4.5+ Earthquakes, Past Week",
    status: 200,
    api: "1.10.3",
    count: 99,
  },
  features: [
    {
      type: "Feature",
      properties: {
        mag: 4.9,
        place: "133 km N of Hihifo, Tonga",
        time: 1703952345726,
        updated: 1703955091040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0mx",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0mx.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 369,
        net: "us",
        code: "6000m0mx",
        ids: ",us6000m0mx,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 18,
        dmin: 2.299,
        rms: 0.89,
        gap: 90,
        magType: "mb",
        type: "earthquake",
        title: "M 4.9 - 133 km N of Hihifo, Tonga",
      },
      geometry: {
        type: "Point",
        coordinates: [-173.9854, -14.7652, 10],
      },
      id: "us6000m0mx",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.2,
        place: "66 km WSW of Panguna, Papua New Guinea",
        time: 1703948583716,
        updated: 1703949719040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0mh",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0mh.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 416,
        net: "us",
        code: "6000m0mh",
        ids: ",us6000m0mh,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 50,
        dmin: 20.411,
        rms: 1.09,
        gap: 72,
        magType: "mww",
        type: "earthquake",
        title: "M 5.2 - 66 km WSW of Panguna, Papua New Guinea",
      },
      geometry: { type: "Point", coordinates: [154.8983, -6.45, 93.12] },
      id: "us6000m0mh",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "116 km SSW of Puerto El Triunfo, El Salvador",
        time: 1703948519404,
        updated: 1703952587040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0me",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0me.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "6000m0me",
        ids: ",us6000m0me,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 32,
        dmin: 1.277,
        rms: 1.26,
        gap: 146,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 116 km SSW of Puerto El Triunfo, El Salvador",
      },
      geometry: { type: "Point", coordinates: [-89.1408, 12.4055, 50.236] },
      id: "us6000m0me",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "109 km SE of Lata, Solomon Islands",
        time: 1703948409991,
        updated: 1703949303040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0mg",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0mg.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "6000m0mg",
        ids: ",us6000m0mg,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 39,
        dmin: 6.695,
        rms: 0.72,
        gap: 116,
        magType: "mww",
        type: "earthquake",
        title: "M 5.1 - 109 km SE of Lata, Solomon Islands",
      },
      geometry: { type: "Point", coordinates: [166.4294, -11.4977, 141.66] },
      id: "us6000m0mg",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "56 km ENE of Luganville, Vanuatu",
        time: 1703918655015,
        updated: 1703919907419,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0k0",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0k0.geojson",
        felt: 1,
        cdi: 2,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "6000m0k0",
        ids: ",us6000m0k0,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 39,
        dmin: 6.092,
        rms: 0.82,
        gap: 130,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 56 km ENE of Luganville, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [167.655, -15.3414, 152.297] },
      id: "us6000m0k0",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.3,
        place: "South Sandwich Islands region",
        time: 1703916998012,
        updated: 1703917913040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0ju",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0ju.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 432,
        net: "us",
        code: "6000m0ju",
        ids: ",us6000m0ju,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 67,
        dmin: 7.681,
        rms: 0.59,
        gap: 61,
        magType: "mb",
        type: "earthquake",
        title: "M 5.3 - South Sandwich Islands region",
      },
      geometry: { type: "Point", coordinates: [-23.3293, -54.6087, 12.97] },
      id: "us6000m0ju",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "19 km S of Shimukappu, Japan",
        time: 1703916451060,
        updated: 1703918875040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0js",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0js.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m0js",
        ids: ",us6000m0js,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 58,
        dmin: 0.967,
        rms: 0.64,
        gap: 91,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 19 km S of Shimukappu, Japan",
      },
      geometry: { type: "Point", coordinates: [142.4472, 42.8275, 49.535] },
      id: "us6000m0js",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.6,
        place: "off the west coast of northern Sumatra",
        time: 1703913566712,
        updated: 1703920992648,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0j8",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0j8.geojson",
        felt: 1,
        cdi: 3.4,
        mmi: 0,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 483,
        net: "us",
        code: "6000m0j8",
        ids: ",us6000m0j8,",
        sources: ",us,",
        types: ",dyfi,losspager,origin,phase-data,shakemap,",
        nst: 167,
        dmin: 4.658,
        rms: 0.51,
        gap: 62,
        magType: "mww",
        type: "earthquake",
        title: "M 5.6 - off the west coast of northern Sumatra",
      },
      geometry: { type: "Point", coordinates: [93.0668, 2.4925, 10] },
      id: "us6000m0j8",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "southern East Pacific Rise",
        time: 1703904145424,
        updated: 1703905651040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0ic",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0ic.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "6000m0ic",
        ids: ",us6000m0ic,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 61,
        dmin: 36.144,
        rms: 1.01,
        gap: 68,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - southern East Pacific Rise",
      },
      geometry: { type: "Point", coordinates: [-116.2072, -49.2847, 10] },
      id: "us6000m0ic",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "92 km WSW of Myitkyina, Myanmar",
        time: 1703867476656,
        updated: 1703868327040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0f0",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0f0.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "6000m0f0",
        ids: ",us6000m0f0,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 53,
        dmin: 4.156,
        rms: 0.78,
        gap: 64,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - 92 km WSW of Myitkyina, Myanmar",
      },
      geometry: { type: "Point", coordinates: [96.5309, 25.105, 10] },
      id: "us6000m0f0",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "Mid-Indian Ridge",
        time: 1703861338686,
        updated: 1703914806040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0et",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0et.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "6000m0et",
        ids: ",us6000m0et,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 89,
        dmin: 12.55,
        rms: 0.58,
        gap: 55,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - Mid-Indian Ridge",
      },
      geometry: { type: "Point", coordinates: [67.8543, -7.1351, 10] },
      id: "us6000m0et",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "49 km NNW of Isangel, Vanuatu",
        time: 1703847768679,
        updated: 1703848966040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0e5",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0e5.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "6000m0e5",
        ids: ",us6000m0e5,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 40,
        dmin: 3.746,
        rms: 0.82,
        gap: 61,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - 49 km NNW of Isangel, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [169.0428, -19.1602, 153.264] },
      id: "us6000m0e5",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "Chagos Archipelago region",
        time: 1703839325747,
        updated: 1703840225040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0dr",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0dr.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "6000m0dr",
        ids: ",us6000m0dr,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 60,
        dmin: 12.776,
        rms: 0.57,
        gap: 54,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - Chagos Archipelago region",
      },
      geometry: { type: "Point", coordinates: [68.0663, -7.2411, 10] },
      id: "us6000m0dr",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "Izu Islands, Japan region",
        time: 1703824734109,
        updated: 1703847584533,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0ch",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0ch.geojson",
        felt: 1,
        cdi: 1,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "6000m0ch",
        ids: ",us6000m0ch,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 74,
        dmin: 1.803,
        rms: 0.7,
        gap: 121,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - Izu Islands, Japan region",
      },
      geometry: { type: "Point", coordinates: [141.7386, 32.3262, 10] },
      id: "us6000m0ch",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.2,
        place: "89 km SW of Panguna, Papua New Guinea",
        time: 1703821039334,
        updated: 1703822757040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0c5",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0c5.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 416,
        net: "us",
        code: "6000m0c5",
        ids: ",us6000m0c5,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 72,
        dmin: 3.924,
        rms: 0.93,
        gap: 60,
        magType: "mb",
        type: "earthquake",
        title: "M 5.2 - 89 km SW of Panguna, Papua New Guinea",
      },
      geometry: { type: "Point", coordinates: [154.9829, -6.9527, 10] },
      id: "us6000m0c5",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "Mid-Indian Ridge",
        time: 1703817490338,
        updated: 1703824999040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0bv",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0bv.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "6000m0bv",
        ids: ",us6000m0bv,",
        sources: ",us,",
        types: ",moment-tensor,origin,phase-data,",
        nst: 53,
        dmin: 12.634,
        rms: 0.74,
        gap: 69,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - Mid-Indian Ridge",
      },
      geometry: { type: "Point", coordinates: [67.9465, -7.1068, 10] },
      id: "us6000m0bv",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.7,
        place: "Mid-Indian Ridge",
        time: 1703812729523,
        updated: 1703899337214,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0b4",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0b4.geojson",
        felt: null,
        cdi: null,
        mmi: 0,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 500,
        net: "us",
        code: "6000m0b4",
        ids: ",us6000m0b4,",
        sources: ",us,",
        types: ",losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 114,
        dmin: 12.613,
        rms: 0.92,
        gap: 40,
        magType: "mww",
        type: "earthquake",
        title: "M 5.7 - Mid-Indian Ridge",
      },
      geometry: { type: "Point", coordinates: [67.9217, -7.1237, 5.688] },
      id: "us6000m0b4",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "100 km SW of Houma, Tonga",
        time: 1703811001213,
        updated: 1703813067040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0az",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0az.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "6000m0az",
        ids: ",us6000m0az,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 28,
        dmin: 0.964,
        rms: 0.41,
        gap: 81,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - 100 km SW of Houma, Tonga",
      },
      geometry: { type: "Point", coordinates: [-175.8867, -21.8981, 153.28] },
      id: "us6000m0az",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.2,
        place: "Mid-Indian Ridge",
        time: 1703810285325,
        updated: 1703825264040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0av",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0av.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 416,
        net: "us",
        code: "6000m0av",
        ids: ",us6000m0av,",
        sources: ",us,",
        types: ",moment-tensor,origin,phase-data,",
        nst: 57,
        dmin: 12.673,
        rms: 0.65,
        gap: 54,
        magType: "mb",
        type: "earthquake",
        title: "M 5.2 - Mid-Indian Ridge",
      },
      geometry: { type: "Point", coordinates: [67.9725, -7.1781, 10] },
      id: "us6000m0av",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "270 km WNW of Houma, Tonga",
        time: 1703809489754,
        updated: 1703811339040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0as",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0as.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m0as",
        ids: ",us6000m0as,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 29,
        dmin: 2.521,
        rms: 0.41,
        gap: 70,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 270 km WNW of Houma, Tonga",
      },
      geometry: { type: "Point", coordinates: [-177.8406, -20.6414, 385.668] },
      id: "us6000m0as",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "69 km NE of Finschhafen, Papua New Guinea",
        time: 1703805808940,
        updated: 1703807471040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0a7",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0a7.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "6000m0a7",
        ids: ",us6000m0a7,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 46,
        dmin: 3.484,
        rms: 0.65,
        gap: 66,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 69 km NE of Finschhafen, Papua New Guinea",
      },
      geometry: { type: "Point", coordinates: [148.2275, -6.0639, 73.434] },
      id: "us6000m0a7",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "Mid-Indian Ridge",
        time: 1703803057476,
        updated: 1703806365040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m0a6",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m0a6.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "6000m0a6",
        ids: ",us6000m0a6,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 26,
        dmin: 7.355,
        rms: 0.6,
        gap: 59,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - Mid-Indian Ridge",
      },
      geometry: { type: "Point", coordinates: [66.4225, -12.9699, 10] },
      id: "us6000m0a6",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.9,
        place: "40 km W of Sola, Vanuatu",
        time: 1703800375868,
        updated: 1703801408040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m09s",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m09s.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 369,
        net: "us",
        code: "6000m09s",
        ids: ",us6000m09s,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 89,
        dmin: 7.244,
        rms: 0.76,
        gap: 52,
        magType: "mb",
        type: "earthquake",
        title: "M 4.9 - 40 km W of Sola, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [167.1815, -13.8184, 206.264] },
      id: "us6000m09s",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.9,
        place: "South Sandwich Islands region",
        time: 1703789831314,
        updated: 1703791980040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m08u",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m08u.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 369,
        net: "us",
        code: "6000m08u",
        ids: ",us6000m08u,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 46,
        dmin: 5.603,
        rms: 0.57,
        gap: 76,
        magType: "mb",
        type: "earthquake",
        title: "M 4.9 - South Sandwich Islands region",
      },
      geometry: { type: "Point", coordinates: [-27.2808, -56.1871, 88.458] },
      id: "us6000m08u",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "210 km ENE of Levuka, Fiji",
        time: 1703781982944,
        updated: 1703783695040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m08b",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m08b.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m08b",
        ids: ",us6000m08b,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 41,
        dmin: 3.013,
        rms: 1,
        gap: 103,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 210 km ENE of Levuka, Fiji",
      },
      geometry: { type: "Point", coordinates: [-178.8035, -17.4457, 553.357] },
      id: "us6000m08b",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "29 km NE of Hinatuan, Philippines",
        time: 1703778513253,
        updated: 1703780448330,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m087",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m087.geojson",
        felt: 1,
        cdi: 2,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "6000m087",
        ids: ",us6000m087,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 84,
        dmin: 1.752,
        rms: 1.14,
        gap: 103,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - 29 km NE of Hinatuan, Philippines",
      },
      geometry: { type: "Point", coordinates: [126.5064, 8.5714, 54.004] },
      id: "us6000m087",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "125 km SE of Kuril’sk, Russia",
        time: 1703775863580,
        updated: 1703778440040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m080",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m080.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "6000m080",
        ids: ",us6000m080,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 107,
        dmin: 4.665,
        rms: 0.64,
        gap: 97,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 125 km SE of Kuril’sk, Russia",
      },
      geometry: { type: "Point", coordinates: [149.0721, 44.4858, 55.554] },
      id: "us6000m080",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "12 km E of Amagi, Japan",
        time: 1703774963634,
        updated: 1703780475322,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m07x",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m07x.geojson",
        felt: 0,
        cdi: 1,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m07x",
        ids: ",us6000m07x,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 40,
        dmin: 1.19,
        rms: 1.12,
        gap: 94,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 12 km E of Amagi, Japan",
      },
      geometry: { type: "Point", coordinates: [129.0247, 27.8244, 55.429] },
      id: "us6000m07x",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "69 km S of Intipucá, El Salvador",
        time: 1703771690624,
        updated: 1703848784395,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m074",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m074.geojson",
        felt: 1,
        cdi: 3.4,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 355,
        net: "us",
        code: "6000m074",
        ids: ",us6000m074,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 74,
        dmin: 0.918,
        rms: 1.2,
        gap: 135,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 69 km S of Intipucá, El Salvador",
      },
      geometry: { type: "Point", coordinates: [-88.0916, 12.5737, 68.08] },
      id: "us6000m074",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "72 km ENE of Hachinohe, Japan",
        time: 1703769415703,
        updated: 1703770786040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m06x",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m06x.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "6000m06x",
        ids: ",us6000m06x,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 50,
        dmin: 0.929,
        rms: 0.92,
        gap: 142,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 72 km ENE of Hachinohe, Japan",
      },
      geometry: { type: "Point", coordinates: [142.2873, 40.7609, 46.69] },
      id: "us6000m06x",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "129 km SE of Kuril’sk, Russia",
        time: 1703767243876,
        updated: 1703768415040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m06q",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m06q.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "6000m06q",
        ids: ",us6000m06q,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 55,
        dmin: 4.717,
        rms: 1.05,
        gap: 135,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 129 km SE of Kuril’sk, Russia",
      },
      geometry: { type: "Point", coordinates: [149.1441, 44.4926, 41] },
      id: "us6000m06q",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "108 km SE of Kuril’sk, Russia",
        time: 1703763851411,
        updated: 1703766534040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m06f",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m06f.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "6000m06f",
        ids: ",us6000m06f,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 51,
        dmin: 4.472,
        rms: 0.66,
        gap: 135,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - 108 km SE of Kuril’sk, Russia",
      },
      geometry: { type: "Point", coordinates: [148.8007, 44.5021, 47.823] },
      id: "us6000m06f",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "South Shetland Islands",
        time: 1703758116089,
        updated: 1703759105040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m05y",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m05y.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "6000m05y",
        ids: ",us6000m05y,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 65,
        dmin: 2.434,
        rms: 0.78,
        gap: 61,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - South Shetland Islands",
      },
      geometry: { type: "Point", coordinates: [-54.1191, -61.1301, 10] },
      id: "us6000m05y",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "127 km SE of Kuril’sk, Russia",
        time: 1703758064527,
        updated: 1703760215040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m05x",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m05x.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m05x",
        ids: ",us6000m05x,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 55,
        dmin: 4.679,
        rms: 0.94,
        gap: 137,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 127 km SE of Kuril’sk, Russia",
      },
      geometry: { type: "Point", coordinates: [149.0921, 44.4657, 44.562] },
      id: "us6000m05x",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "127 km SE of Kuril’sk, Russia",
        time: 1703756246918,
        updated: 1703757410040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m05n",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m05n.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "6000m05n",
        ids: ",us6000m05n,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 85,
        dmin: 4.668,
        rms: 0.79,
        gap: 135,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - 127 km SE of Kuril’sk, Russia",
      },
      geometry: { type: "Point", coordinates: [149.0769, 44.4565, 40.054] },
      id: "us6000m05n",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "17 km SSE of Akçadağ, Turkey",
        time: 1703756047007,
        updated: 1703770403046,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m05l",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m05l.geojson",
        felt: 3,
        cdi: 5.9,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 313,
        net: "us",
        code: "6000m05l",
        ids: ",us6000m05l,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 52,
        dmin: 0.912,
        rms: 0.75,
        gap: 37,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 17 km SSE of Akçadağ, Turkey",
      },
      geometry: { type: "Point", coordinates: [38.0774, 38.2026, 10] },
      id: "us6000m05l",
    },
    {
      type: "Feature",
      properties: {
        mag: 6.5,
        place: "113 km SE of Kuril’sk, Russia",
        time: 1703754915393,
        updated: 1703842037625,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m05c",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m05c.geojson",
        felt: 3,
        cdi: 6.3,
        mmi: 4.556,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 652,
        net: "us",
        code: "6000m05c",
        ids: ",us6000m05c,",
        sources: ",us,",
        types:
          ",dyfi,ground-failure,losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 119,
        dmin: 4.611,
        rms: 1.07,
        gap: 49,
        magType: "mww",
        type: "earthquake",
        title: "M 6.5 - 113 km SE of Kuril’sk, Russia",
      },
      geometry: { type: "Point", coordinates: [148.9903, 44.5796, 23.844] },
      id: "us6000m05c",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.8,
        place: "Pacific-Antarctic Ridge",
        time: 1703754780076,
        updated: 1703842122788,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m05d",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m05d.geojson",
        felt: null,
        cdi: null,
        mmi: 6.936,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 518,
        net: "us",
        code: "6000m05d",
        ids: ",us6000m05d,",
        sources: ",us,",
        types: ",losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 31,
        dmin: 13.063,
        rms: 0.83,
        gap: 113,
        magType: "mww",
        type: "earthquake",
        title: "M 5.8 - Pacific-Antarctic Ridge",
      },
      geometry: { type: "Point", coordinates: [-179.6522, -65.4948, 10] },
      id: "us6000m05d",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.2,
        place: "14 km ENE of Suyan, Philippines",
        time: 1703727311006,
        updated: 1703773021637,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m040",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m040.geojson",
        felt: 11,
        cdi: 4.4,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 421,
        net: "us",
        code: "6000m040",
        ids: ",us6000m040,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 85,
        dmin: 0.955,
        rms: 0.59,
        gap: 67,
        magType: "mb",
        type: "earthquake",
        title: "M 5.2 - 14 km ENE of Suyan, Philippines",
      },
      geometry: { type: "Point", coordinates: [125.5027, 6.1115, 35] },
      id: "us6000m040",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "78 km W of San Antonio de los Cobres, Argentina",
        time: 1703722484681,
        updated: 1703725523040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m03v",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m03v.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m03v",
        ids: ",us6000m03v,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 24,
        dmin: 1.589,
        rms: 0.87,
        gap: 96,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 78 km W of San Antonio de los Cobres, Argentina",
      },
      geometry: { type: "Point", coordinates: [-67.0941, -24.196, 215.021] },
      id: "us6000m03v",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.2,
        place: "Reykjanes Ridge",
        time: 1703720017683,
        updated: 1703720991040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m03g",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m03g.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 416,
        net: "us",
        code: "6000m03g",
        ids: ",us6000m03g,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 120,
        dmin: 7.561,
        rms: 0.91,
        gap: 47,
        magType: "mb",
        type: "earthquake",
        title: "M 5.2 - Reykjanes Ridge",
      },
      geometry: { type: "Point", coordinates: [-34.1338, 56.3922, 10] },
      id: "us6000m03g",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "52 km SSW of Singaparna, Indonesia",
        time: 1703717036769,
        updated: 1703773637040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m02j",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m02j.geojson",
        felt: 5,
        cdi: 3.3,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 402,
        net: "us",
        code: "6000m02j",
        ids: ",us6000m02j,",
        sources: ",us,",
        types: ",dyfi,moment-tensor,origin,phase-data,",
        nst: 75,
        dmin: 0.438,
        rms: 0.89,
        gap: 39,
        magType: "mww",
        type: "earthquake",
        title: "M 5.1 - 52 km SSW of Singaparna, Indonesia",
      },
      geometry: { type: "Point", coordinates: [107.9423, -7.7936, 71.557] },
      id: "us6000m02j",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.7,
        place: "southern East Pacific Rise",
        time: 1703712798074,
        updated: 1703799450440,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m02b",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m02b.geojson",
        felt: null,
        cdi: null,
        mmi: 0,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 500,
        net: "us",
        code: "6000m02b",
        ids: ",us6000m02b,",
        sources: ",us,",
        types: ",losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 65,
        dmin: 28.06,
        rms: 1.45,
        gap: 46,
        magType: "mww",
        type: "earthquake",
        title: "M 5.7 - southern East Pacific Rise",
      },
      geometry: { type: "Point", coordinates: [-118.3022, -53.1034, 10] },
      id: "us6000m02b",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "26 km NNE of Kupang, Indonesia",
        time: 1703703159931,
        updated: 1703758567919,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m01a",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m01a.geojson",
        felt: 4,
        cdi: 6.3,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 387,
        net: "us",
        code: "6000m01a",
        ids: ",us6000m01a,",
        sources: ",us,",
        types: ",dyfi,moment-tensor,origin,phase-data,",
        nst: 77,
        dmin: 5.969,
        rms: 0.75,
        gap: 54,
        magType: "mww",
        type: "earthquake",
        title: "M 5.0 - 26 km NNE of Kupang, Indonesia",
      },
      geometry: { type: "Point", coordinates: [123.7173, -9.9603, 10] },
      id: "us6000m01a",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "Reykjanes Ridge",
        time: 1703691637149,
        updated: 1703692695040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m00j",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m00j.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "6000m00j",
        ids: ",us6000m00j,",
        sources: ",us,",
        types: ",moment-tensor,origin,phase-data,",
        nst: 111,
        dmin: 10.403,
        rms: 1.09,
        gap: 47,
        magType: "mww",
        type: "earthquake",
        title: "M 5.0 - Reykjanes Ridge",
      },
      geometry: { type: "Point", coordinates: [-33.9309, 56.3915, 10] },
      id: "us6000m00j",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.4,
        place: "southern East Pacific Rise",
        time: 1703691367336,
        updated: 1703788380040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m00n",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m00n.geojson",
        felt: null,
        cdi: null,
        mmi: 0,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 449,
        net: "us",
        code: "6000m00n",
        ids: ",us6000m00n,",
        sources: ",us,",
        types: ",losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 68,
        dmin: 33.391,
        rms: 0.72,
        gap: 64,
        magType: "mww",
        type: "earthquake",
        title: "M 5.4 - southern East Pacific Rise",
      },
      geometry: { type: "Point", coordinates: [-117.8243, -53.1119, 10] },
      id: "us6000m00n",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "20 km SE of İhsangazi, Turkey",
        time: 1703682252375,
        updated: 1703758861042,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m009",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m009.geojson",
        felt: 2,
        cdi: 5.2,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 341,
        net: "us",
        code: "6000m009",
        ids: ",us6000m009,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 87,
        dmin: 0.886,
        rms: 0.82,
        gap: 31,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - 20 km SE of İhsangazi, Turkey",
      },
      geometry: { type: "Point", coordinates: [33.7452, 41.0948, 6.51] },
      id: "us6000m009",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "119 km NNE of Port-Vila, Vanuatu",
        time: 1703676970538,
        updated: 1703677918040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000m003",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000m003.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000m003",
        ids: ",us6000m003,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 24,
        dmin: 5.802,
        rms: 0.44,
        gap: 252,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 119 km NNE of Port-Vila, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [168.8281, -16.7783, 221.204] },
      id: "us6000m003",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "96 km S of Puerto San José, Guatemala",
        time: 1703669742204,
        updated: 1703671119040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000lzzs",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000lzzs.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "6000lzzs",
        ids: ",us6000lzzs,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 48,
        dmin: 1.379,
        rms: 0.89,
        gap: 185,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 96 km S of Puerto San José, Guatemala",
      },
      geometry: { type: "Point", coordinates: [-90.9055, 13.0587, 37.627] },
      id: "us6000lzzs",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "67 km SSE of Akutan, Alaska",
        time: 1703657818894,
        updated: 1703745531860,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000lzz1",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000lzz1.geojson",
        felt: 1,
        cdi: 2.7,
        mmi: 2.46,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "6000lzz1",
        ids: ",us6000lzz1,ak023gl4oeun,",
        sources: ",us,ak,",
        types: ",dyfi,origin,phase-data,shakemap,",
        nst: 60,
        dmin: 0.778,
        rms: 1.22,
        gap: 161,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 67 km SSE of Akutan, Alaska",
      },
      geometry: { type: "Point", coordinates: [-165.2554, 53.6129, 57.524] },
      id: "us6000lzz1",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.3,
        place: "93 km SSE of Kirensk, Russia",
        time: 1703653759977,
        updated: 1703654628040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000lzyw",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000lzyw.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 432,
        net: "us",
        code: "6000lzyw",
        ids: ",us6000lzyw,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 87,
        dmin: 6.105,
        rms: 0.76,
        gap: 24,
        magType: "mb",
        type: "earthquake",
        title: "M 5.3 - 93 km SSE of Kirensk, Russia",
      },
      geometry: { type: "Point", coordinates: [108.7154, 57.0074, 10] },
      id: "us6000lzyw",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "Fiji region",
        time: 1703634110410,
        updated: 1703634953040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000lzxw",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000lzxw.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "6000lzxw",
        ids: ",us6000lzxw,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 46,
        dmin: 3.177,
        rms: 1.02,
        gap: 83,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - Fiji region",
      },
      geometry: { type: "Point", coordinates: [-178.6057, -21.0873, 537.213] },
      id: "us6000lzxw",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "40 km SSW of Shizunai-furukawachō, Japan",
        time: 1703631237545,
        updated: 1703632260040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000lzxt",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000lzxt.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "6000lzxt",
        ids: ",us6000lzxt,",
        sources: ",us,",
        types: ",moment-tensor,origin,phase-data,",
        nst: 72,
        dmin: 0.665,
        rms: 0.95,
        gap: 88,
        magType: "mwr",
        type: "earthquake",
        title: "M 4.7 - 40 km SSW of Shizunai-furukawachō, Japan",
      },
      geometry: { type: "Point", coordinates: [142.2666, 41.976, 62.387] },
      id: "us6000lzxt",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "20 km SSE of Popova, Russia",
        time: 1703617822228,
        updated: 1703618889040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us6000lzww",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us6000lzww.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "6000lzww",
        ids: ",us6000lzww,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 148,
        dmin: 1.416,
        rms: 0.69,
        gap: 28,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 20 km SSE of Popova, Russia",
      },
      geometry: { type: "Point", coordinates: [131.8056, 42.7899, 519.166] },
      id: "us6000lzww",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "23 km ESE of Dabajuro, Venezuela",
        time: 1703607090536,
        updated: 1703621393040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llij",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llij.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "7000llij",
        ids: ",us7000llij,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 55,
        dmin: 1.666,
        rms: 0.75,
        gap: 45,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 23 km ESE of Dabajuro, Venezuela",
      },
      geometry: { type: "Point", coordinates: [-70.4958, 10.9093, 18.164] },
      id: "us7000llij",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "Izu Islands, Japan region",
        time: 1703603178927,
        updated: 1703620253040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llid",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llid.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000llid",
        ids: ",us7000llid,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 95,
        dmin: 1.623,
        rms: 0.8,
        gap: 77,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - Izu Islands, Japan region",
      },
      geometry: { type: "Point", coordinates: [139.721, 31.4896, 10] },
      id: "us7000llid",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "South Sandwich Islands region",
        time: 1703599975324,
        updated: 1703601195040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000lli4",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000lli4.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "7000lli4",
        ids: ",us7000lli4,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 59,
        dmin: 5.692,
        rms: 0.96,
        gap: 82,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - South Sandwich Islands region",
      },
      geometry: { type: "Point", coordinates: [-27.2428, -56.4209, 125.043] },
      id: "us7000lli4",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "56 km W of Madang, Papua New Guinea",
        time: 1703596302790,
        updated: 1703597280846,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llhv",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llhv.geojson",
        felt: 1,
        cdi: 3.1,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "7000llhv",
        ids: ",us7000llhv,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 73,
        dmin: 4.558,
        rms: 0.56,
        gap: 61,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - 56 km W of Madang, Papua New Guinea",
      },
      geometry: { type: "Point", coordinates: [145.277, -5.2199, 80.482] },
      id: "us7000llhv",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.9,
        place: "276 km NE of Hadibu, Yemen",
        time: 1703594299898,
        updated: 1703595363040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llht",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llht.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 369,
        net: "us",
        code: "7000llht",
        ids: ",us7000llht,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 72,
        dmin: 10.206,
        rms: 0.73,
        gap: 98,
        magType: "mb",
        type: "earthquake",
        title: "M 4.9 - 276 km NE of Hadibu, Yemen",
      },
      geometry: { type: "Point", coordinates: [55.4661, 14.7101, 10] },
      id: "us7000llht",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "70 km ENE of Barcelona, Philippines",
        time: 1703586027508,
        updated: 1703586923040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llh7",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llh7.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000llh7",
        ids: ",us7000llh7,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 56,
        dmin: 1.97,
        rms: 0.55,
        gap: 72,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 70 km ENE of Barcelona, Philippines",
      },
      geometry: { type: "Point", coordinates: [126.999, 8.4582, 61.177] },
      id: "us7000llh7",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "south of the Fiji Islands",
        time: 1703577278890,
        updated: 1703578342040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llgs",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llgs.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000llgs",
        ids: ",us7000llgs,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 24,
        dmin: 2.906,
        rms: 0.43,
        gap: 126,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - south of the Fiji Islands",
      },
      geometry: { type: "Point", coordinates: [-177.5523, -26.3628, 187.842] },
      id: "us7000llgs",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.3,
        place: "72 km NE of Samaná, Dominican Republic",
        time: 1703575465190,
        updated: 1703612265458,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/pr2023360000",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/pr2023360000.geojson",
        felt: 35,
        cdi: 3.8,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 445,
        net: "pr",
        code: "2023360000",
        ids: ",pt23360050,us7000llgi,pr2023360000,",
        sources: ",pt,us,pr,",
        types: ",dyfi,origin,phase-data,",
        nst: 26,
        dmin: 0.513,
        rms: 0.51,
        gap: 248,
        magType: "ml",
        type: "earthquake",
        title: "M 5.3 - 72 km NE of Samaná, Dominican Republic",
      },
      geometry: { type: "Point", coordinates: [-68.8005, 19.6258, 9] },
      id: "pr2023360000",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "191 km SE of Sarangani, Philippines",
        time: 1703572957607,
        updated: 1703574152040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llge",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llge.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000llge",
        ids: ",us7000llge,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 28,
        dmin: 3.095,
        rms: 0.79,
        gap: 113,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 191 km SE of Sarangani, Philippines",
      },
      geometry: { type: "Point", coordinates: [126.6458, 4.1428, 59.686] },
      id: "us7000llge",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.9,
        place: "Izu Islands, Japan region",
        time: 1703572257690,
        updated: 1703573192040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llgb",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llgb.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 369,
        net: "us",
        code: "7000llgb",
        ids: ",us7000llgb,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 115,
        dmin: 2.866,
        rms: 0.71,
        gap: 65,
        magType: "mb",
        type: "earthquake",
        title: "M 4.9 - Izu Islands, Japan region",
      },
      geometry: { type: "Point", coordinates: [138.5677, 30.4453, 431.336] },
      id: "us7000llgb",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "92 km W of Diego de Almagro, Chile",
        time: 1703564922184,
        updated: 1703652639040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llfx",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llfx.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "7000llfx",
        ids: ",us7000llfx,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 27,
        dmin: 0.368,
        rms: 0.44,
        gap: 159,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 92 km W of Diego de Almagro, Chile",
      },
      geometry: { type: "Point", coordinates: [-70.9694, -26.3057, 35] },
      id: "us7000llfx",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "30 km W of Dompu, Indonesia",
        time: 1703561498669,
        updated: 1703651744040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llfs",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llfs.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "7000llfs",
        ids: ",us7000llfs,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 25,
        dmin: 0.487,
        rms: 0.26,
        gap: 92,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - 30 km W of Dompu, Indonesia",
      },
      geometry: { type: "Point", coordinates: [118.1895, -8.5608, 140.359] },
      id: "us7000llfs",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "25 km S of Thang, India",
        time: 1703545433692,
        updated: 1703844393195,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llf2",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llf2.geojson",
        felt: 1,
        cdi: 1,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000llf2",
        ids: ",us7000llf2,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 62,
        dmin: 3.067,
        rms: 0.47,
        gap: 79,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 25 km S of Thang, India",
      },
      geometry: { type: "Point", coordinates: [76.746, 34.7015, 13.961] },
      id: "us7000llf2",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "southeast of Easter Island",
        time: 1703537256320,
        updated: 1703541595040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llel",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llel.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000llel",
        ids: ",us7000llel,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 41,
        dmin: 13.177,
        rms: 0.97,
        gap: 104,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - southeast of Easter Island",
      },
      geometry: { type: "Point", coordinates: [-90.826, -41.3571, 10] },
      id: "us7000llel",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "146 km S of False Pass, Alaska",
        time: 1703525555682,
        updated: 1703527254972,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000lldz",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000lldz.geojson",
        felt: null,
        cdi: null,
        mmi: 1.755,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000lldz",
        ids: ",ak023gi08wby,us7000lldz,",
        sources: ",ak,us,",
        types: ",origin,phase-data,shakemap,",
        nst: 45,
        dmin: 1.214,
        rms: 0.97,
        gap: 167,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 146 km S of False Pass, Alaska",
      },
      geometry: { type: "Point", coordinates: [-163.4603, 53.5367, 21.628] },
      id: "us7000lldz",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "203 km NW of Attu Station, Alaska",
        time: 1703499274980,
        updated: 1703661312040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llcl",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llcl.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000llcl",
        ids: ",us7000llcl,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 64,
        dmin: 2.359,
        rms: 0.74,
        gap: 94,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 203 km NW of Attu Station, Alaska",
      },
      geometry: { type: "Point", coordinates: [170.7034, 53.9181, 10] },
      id: "us7000llcl",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "northern Mid-Atlantic Ridge",
        time: 1703498174490,
        updated: 1703504415040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llch",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llch.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000llch",
        ids: ",us7000llch,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 29,
        dmin: 22.523,
        rms: 0.76,
        gap: 70,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - northern Mid-Atlantic Ridge",
      },
      geometry: { type: "Point", coordinates: [-41.8973, 30.0081, 10] },
      id: "us7000llch",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "southeast of Easter Island",
        time: 1703487055753,
        updated: 1703758502040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000lldl",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000lldl.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "7000lldl",
        ids: ",us7000lldl,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 51,
        dmin: 12.217,
        rms: 0.62,
        gap: 207,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - southeast of Easter Island",
      },
      geometry: { type: "Point", coordinates: [-100.1368, -36.5133, 10] },
      id: "us7000lldl",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "25 km SE of Gorontalo, Indonesia",
        time: 1703485849302,
        updated: 1703486782040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llc0",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llc0.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000llc0",
        ids: ",us7000llc0,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 44,
        dmin: 1.454,
        rms: 0.82,
        gap: 74,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 25 km SE of Gorontalo, Indonesia",
      },
      geometry: { type: "Point", coordinates: [123.2042, 0.3557, 232.745] },
      id: "us7000llc0",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "161 km SE of Shima, Japan",
        time: 1703479741152,
        updated: 1703645262040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llbp",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llbp.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "7000llbp",
        ids: ",us7000llbp,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 120,
        dmin: 1.569,
        rms: 0.68,
        gap: 33,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - 161 km SE of Shima, Japan",
      },
      geometry: { type: "Point", coordinates: [137.8227, 33.1337, 331.236] },
      id: "us7000llbp",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.5,
        place: "82 km N of Finschhafen, Papua New Guinea",
        time: 1703474432253,
        updated: 1703637037040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llbg",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llbg.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 312,
        net: "us",
        code: "7000llbg",
        ids: ",us7000llbg,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 31,
        dmin: 3.643,
        rms: 0.49,
        gap: 45,
        magType: "mb",
        type: "earthquake",
        title: "M 4.5 - 82 km N of Finschhafen, Papua New Guinea",
      },
      geometry: { type: "Point", coordinates: [147.9151, -5.8158, 117.074] },
      id: "us7000llbg",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "South Sandwich Islands region",
        time: 1703457240943,
        updated: 1703458185040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llax",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llax.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "7000llax",
        ids: ",us7000llax,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 43,
        dmin: 6.605,
        rms: 0.67,
        gap: 83,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - South Sandwich Islands region",
      },
      geometry: { type: "Point", coordinates: [-25.3093, -55.8123, 10] },
      id: "us7000llax",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "76 km ESE of Sarangani, Philippines",
        time: 1703449914107,
        updated: 1703451397040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llag",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llag.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000llag",
        ids: ",us7000llag,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 42,
        dmin: 2.055,
        rms: 0.45,
        gap: 101,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 76 km ESE of Sarangani, Philippines",
      },
      geometry: { type: "Point", coordinates: [126.0599, 5.0575, 108.646] },
      id: "us7000llag",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "South Sandwich Islands region",
        time: 1703448629144,
        updated: 1703449834040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000llad",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000llad.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000llad",
        ids: ",us7000llad,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 42,
        dmin: 7.543,
        rms: 0.53,
        gap: 92,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - South Sandwich Islands region",
      },
      geometry: { type: "Point", coordinates: [-28.007, -60.2555, 10] },
      id: "us7000llad",
    },
    {
      type: "Feature",
      properties: {
        mag: 5,
        place: "152 km ESE of Petropavlovsk-Kamchatsky, Russia",
        time: 1703443363997,
        updated: 1703444531040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000lla8",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000lla8.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 385,
        net: "us",
        code: "7000lla8",
        ids: ",us7000lla8,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 89,
        dmin: 1.348,
        rms: 0.78,
        gap: 106,
        magType: "mb",
        type: "earthquake",
        title: "M 5.0 - 152 km ESE of Petropavlovsk-Kamchatsky, Russia",
      },
      geometry: { type: "Point", coordinates: [160.8453, 52.7993, 27.746] },
      id: "us7000lla8",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "south of the Kermadec Islands",
        time: 1703442041090,
        updated: 1703444133040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000lla2",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000lla2.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000lla2",
        ids: ",us7000lla2,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 36,
        dmin: 3.308,
        rms: 0.85,
        gap: 150,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - south of the Kermadec Islands",
      },
      geometry: { type: "Point", coordinates: [-179.3586, -32.3395, 371.454] },
      id: "us7000lla2",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "Mid-Indian Ridge",
        time: 1703440929639,
        updated: 1703443313040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000lla1",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000lla1.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000lla1",
        ids: ",us7000lla1,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 51,
        dmin: 12.252,
        rms: 0.58,
        gap: 62,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - Mid-Indian Ridge",
      },
      geometry: { type: "Point", coordinates: [66.987, -15.1447, 10] },
      id: "us7000lla1",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "South Sandwich Islands region",
        time: 1703439244578,
        updated: 1703440175040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll9x",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll9x.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000ll9x",
        ids: ",us7000ll9x,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 34,
        dmin: 15.739,
        rms: 0.42,
        gap: 81,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - South Sandwich Islands region",
      },
      geometry: { type: "Point", coordinates: [-25.7861, -59.0077, 46.746] },
      id: "us7000ll9x",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.4,
        place: "131 km ENE of ‘Ohonua, Tonga",
        time: 1703429575297,
        updated: 1703516215490,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll9h",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll9h.geojson",
        felt: 1,
        cdi: 2.7,
        mmi: 3.092,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 449,
        net: "us",
        code: "7000ll9h",
        ids: ",us7000ll9h,",
        sources: ",us,",
        types: ",dyfi,losspager,origin,phase-data,shakemap,",
        nst: 42,
        dmin: 1.365,
        rms: 1.05,
        gap: 91,
        magType: "mww",
        type: "earthquake",
        title: "M 5.4 - 131 km ENE of ‘Ohonua, Tonga",
      },
      geometry: { type: "Point", coordinates: [-173.7618, -20.9451, 10] },
      id: "us7000ll9h",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "58 km NNW of Yonakuni, Japan",
        time: 1703424130819,
        updated: 1703426865040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll8w",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll8w.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000ll8w",
        ids: ",us7000ll8w,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 27,
        dmin: 0.528,
        rms: 1.14,
        gap: 81,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 58 km NNW of Yonakuni, Japan",
      },
      geometry: { type: "Point", coordinates: [122.7438, 24.938, 10] },
      id: "us7000ll8w",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.9,
        place: "Izu Islands, Japan region",
        time: 1703418389237,
        updated: 1703419351040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll8d",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll8d.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 369,
        net: "us",
        code: "7000ll8d",
        ids: ",us7000ll8d,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 78,
        dmin: 2.475,
        rms: 0.88,
        gap: 124,
        magType: "mb",
        type: "earthquake",
        title: "M 4.9 - Izu Islands, Japan region",
      },
      geometry: { type: "Point", coordinates: [142.7203, 32.7293, 10] },
      id: "us7000ll8d",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.7,
        place: "11 km NNE of Hinatuan, Philippines",
        time: 1703407917640,
        updated: 1703417847442,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll7t",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll7t.geojson",
        felt: 1,
        cdi: 2,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 340,
        net: "us",
        code: "7000ll7t",
        ids: ",us7000ll7t,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 63,
        dmin: 1.596,
        rms: 0.72,
        gap: 92,
        magType: "mb",
        type: "earthquake",
        title: "M 4.7 - 11 km NNE of Hinatuan, Philippines",
      },
      geometry: { type: "Point", coordinates: [126.3738, 8.4665, 64.666] },
      id: "us7000ll7t",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "61 km NNE of Pototano, Indonesia",
        time: 1703397652605,
        updated: 1703401723040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll6z",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll6z.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000ll6z",
        ids: ",us7000ll6z,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 25,
        dmin: 0.895,
        rms: 0.9,
        gap: 83,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 61 km NNE of Pototano, Indonesia",
      },
      geometry: { type: "Point", coordinates: [117.7542, -7.9267, 18.67] },
      id: "us7000ll6z",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "59 km WSW of Cañete, Chile",
        time: 1703388768383,
        updated: 1703427627952,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll6j",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll6j.geojson",
        felt: 2,
        cdi: 4.1,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 401,
        net: "us",
        code: "7000ll6j",
        ids: ",us7000ll6j,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 41,
        dmin: 1.48,
        rms: 0.82,
        gap: 148,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - 59 km WSW of Cañete, Chile",
      },
      geometry: { type: "Point", coordinates: [-73.9675, -38.0945, 10] },
      id: "us7000ll6j",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.9,
        place: "52 km SW of Cañete, Chile",
        time: 1703388222644,
        updated: 1703607672040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll6h",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll6h.geojson",
        felt: 13,
        cdi: 4.3,
        mmi: 5.512,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 541,
        net: "us",
        code: "7000ll6h",
        ids: ",us7000ll6h,",
        sources: ",us,",
        types: ",dyfi,losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 60,
        dmin: 1.435,
        rms: 1.21,
        gap: 131,
        magType: "mww",
        type: "earthquake",
        title: "M 5.9 - 52 km SW of Cañete, Chile",
      },
      geometry: { type: "Point", coordinates: [-73.8819, -38.0756, 11.8] },
      id: "us7000ll6h",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.1,
        place: "34 km ENE of Hinatuan, Philippines",
        time: 1703386926323,
        updated: 1703388320040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll6e",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll6e.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 400,
        net: "us",
        code: "7000ll6e",
        ids: ",us7000ll6e,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 73,
        dmin: 1.772,
        rms: 0.89,
        gap: 68,
        magType: "mb",
        type: "earthquake",
        title: "M 5.1 - 34 km ENE of Hinatuan, Philippines",
      },
      geometry: { type: "Point", coordinates: [126.5959, 8.5374, 51.369] },
      id: "us7000ll6e",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "113 km SSW of Isangel, Vanuatu",
        time: 1703386479844,
        updated: 1703387753040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll6d",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll6d.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000ll6d",
        ids: ",us7000ll6d,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 25,
        dmin: 2.508,
        rms: 0.86,
        gap: 113,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 113 km SSW of Isangel, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [168.9473, -20.5197, 10] },
      id: "us7000ll6d",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.3,
        place: "171 km SSW of ‘Ohonua, Tonga",
        time: 1703384537046,
        updated: 1703387997835,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll64",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll64.geojson",
        felt: 2,
        cdi: 2.7,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 433,
        net: "us",
        code: "7000ll64",
        ids: ",us7000ll64,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 87,
        dmin: 1.626,
        rms: 1.2,
        gap: 30,
        magType: "mww",
        type: "earthquake",
        title: "M 5.3 - 171 km SSW of ‘Ohonua, Tonga",
      },
      geometry: { type: "Point", coordinates: [-175.6595, -22.7476, 48.545] },
      id: "us7000ll64",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.3,
        place: "74 km ENE of Barcelona, Philippines",
        time: 1703384444838,
        updated: 1703387400483,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll63",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll63.geojson",
        felt: 1,
        cdi: 2,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 432,
        net: "us",
        code: "7000ll63",
        ids: ",us7000ll63,",
        sources: ",us,",
        types: ",dyfi,origin,phase-data,",
        nst: 70,
        dmin: 1.954,
        rms: 0.75,
        gap: 83,
        magType: "mb",
        type: "earthquake",
        title: "M 5.3 - 74 km ENE of Barcelona, Philippines",
      },
      geometry: { type: "Point", coordinates: [127.0931, 8.329, 63.324] },
      id: "us7000ll63",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.8,
        place: "116 km SSW of Isangel, Vanuatu",
        time: 1703383180048,
        updated: 1703469833565,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll61",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll61.geojson",
        felt: null,
        cdi: null,
        mmi: 3.563,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 518,
        net: "us",
        code: "7000ll61",
        ids: ",us7000ll61,",
        sources: ",us,",
        types: ",losspager,origin,phase-data,shakemap,",
        nst: 66,
        dmin: 2.476,
        rms: 1.31,
        gap: 66,
        magType: "mww",
        type: "earthquake",
        title: "M 5.8 - 116 km SSW of Isangel, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [168.9082, -20.5344, 10] },
      id: "us7000ll61",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.6,
        place: "122 km SE of Pangai, Tonga",
        time: 1703375086342,
        updated: 1703509404040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll5l",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll5l.geojson",
        felt: 0,
        cdi: 1,
        mmi: 3.33,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 482,
        net: "us",
        code: "7000ll5l",
        ids: ",us7000ll5l,",
        sources: ",us,",
        types: ",dyfi,losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 56,
        dmin: 1.846,
        rms: 0.97,
        gap: 133,
        magType: "mww",
        type: "earthquake",
        title: "M 5.6 - 122 km SE of Pangai, Tonga",
      },
      geometry: { type: "Point", coordinates: [-173.3877, -20.4439, 10] },
      id: "us7000ll5l",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.8,
        place: "107 km SSW of Isangel, Vanuatu",
        time: 1703366254179,
        updated: 1703368654040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll4w",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll4w.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 354,
        net: "us",
        code: "7000ll4w",
        ids: ",us7000ll4w,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 25,
        dmin: 2.59,
        rms: 0.6,
        gap: 79,
        magType: "mb",
        type: "earthquake",
        title: "M 4.8 - 107 km SSW of Isangel, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [169.0573, -20.4904, 34.501] },
      id: "us7000ll4w",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.2,
        place: "111 km SSW of Isangel, Vanuatu",
        time: 1703364228529,
        updated: 1703365900040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll4n",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll4n.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 416,
        net: "us",
        code: "7000ll4n",
        ids: ",us7000ll4n,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 37,
        dmin: 2.529,
        rms: 0.76,
        gap: 123,
        magType: "mww",
        type: "earthquake",
        title: "M 5.2 - 111 km SSW of Isangel, Vanuatu",
      },
      geometry: { type: "Point", coordinates: [168.9436, -20.4925, 23.972] },
      id: "us7000ll4n",
    },
    {
      type: "Feature",
      properties: {
        mag: 4.6,
        place: "76 km WNW of Vallenar, Chile",
        time: 1703357304763,
        updated: 1703373046040,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll4d",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll4d.geojson",
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: "reviewed",
        tsunami: 0,
        sig: 326,
        net: "us",
        code: "7000ll4d",
        ids: ",us7000ll4d,",
        sources: ",us,",
        types: ",origin,phase-data,",
        nst: 36,
        dmin: 0.948,
        rms: 0.96,
        gap: 147,
        magType: "mb",
        type: "earthquake",
        title: "M 4.6 - 76 km WNW of Vallenar, Chile",
      },
      geometry: { type: "Point", coordinates: [-71.5154, -28.3877, 24.474] },
      id: "us7000ll4d",
    },
    {
      type: "Feature",
      properties: {
        mag: 5.8,
        place: "115 km SSE of Vilyuchinsk, Russia",
        time: 1703353683605,
        updated: 1703603902925,
        tz: null,
        url: "https://earthquake.usgs.gov/earthquakes/eventpage/us7000ll46",
        detail:
          "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us7000ll46.geojson",
        felt: 1,
        cdi: 3.4,
        mmi: 4.016,
        alert: "green",
        status: "reviewed",
        tsunami: 0,
        sig: 518,
        net: "us",
        code: "7000ll46",
        ids: ",us7000ll46,",
        sources: ",us,",
        types: ",dyfi,losspager,moment-tensor,origin,phase-data,shakemap,",
        nst: 410,
        dmin: 1.091,
        rms: 0.66,
        gap: 14,
        magType: "mww",
        type: "earthquake",
        title: "M 5.8 - 115 km SSE of Vilyuchinsk, Russia",
      },
      geometry: { type: "Point", coordinates: [158.9576, 51.9509, 29] },
      id: "us7000ll46",
    },
  ],
  bbox: [-179.6522, -65.4948, 5.688, 170.7034, 57.0074, 553.357],
};
